<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1e293b; line-height: 1.6; max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: #1e293b; color: white; padding: 20px 24px; border-radius: 8px 8px 0 0; }
        .header h1 { margin: 0; font-size: 20px; }
        .content { background: #f8fafc; padding: 24px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 8px 8px; }
        .stat { display: inline-block; text-align: center; padding: 12px 20px; margin: 4px; background: white; border-radius: 6px; border: 1px solid #e2e8f0; }
        .stat-value { font-size: 24px; font-weight: 700; color: #1e293b; }
        .stat-label { font-size: 12px; color: #64748b; text-transform: uppercase; }
        table { width: 100%; border-collapse: collapse; margin: 16px 0; }
        th { text-align: left; padding: 8px 12px; background: #e2e8f0; font-size: 12px; text-transform: uppercase; color: #64748b; }
        td { padding: 8px 12px; border-bottom: 1px solid #e2e8f0; font-size: 13px; }
        .footer { text-align: center; padding: 16px; color: #94a3b8; font-size: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>HashGuardian {{ ucfirst($reportData['period'] ?? 'Daily') }} Digest</h1>
        <p style="margin:8px 0 0; opacity:0.8; font-size:13px;">{{ $reportData['from'] ?? '' }} &mdash; {{ $reportData['to'] ?? '' }}</p>
    </div>
    <div class="content">
        <div style="text-align:center; margin-bottom:20px;">
            @php $c = $reportData['counts'] ?? []; $rs = $reportData['request_stats'] ?? []; @endphp
            <div class="stat"><div class="stat-value">{{ number_format($c['request'] ?? 0) }}</div><div class="stat-label">Requests</div></div>
            <div class="stat"><div class="stat-value">{{ number_format($c['exception'] ?? 0) }}</div><div class="stat-label">Exceptions</div></div>
            <div class="stat"><div class="stat-value">{{ number_format($rs['avg_duration'] ?? 0, 0) }}ms</div><div class="stat-label">Avg Response</div></div>
            <div class="stat"><div class="stat-value">{{ number_format($c['job'] ?? 0) }}</div><div class="stat-label">Jobs</div></div>
        </div>

        @if(! empty($reportData['top_exceptions']))
            <h3 style="font-size:14px; margin-bottom:8px;">Top Exceptions</h3>
            <table>
                <thead><tr><th>Exception</th><th>Message</th></tr></thead>
                <tbody>
                    @foreach($reportData['top_exceptions'] as $ex)
                        <tr>
                            <td style="font-weight:600; color:#ef4444;">{{ $ex['class'] ?? 'Unknown' }}</td>
                            <td>{{ $ex['message'] ?? '' }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endif
    </div>
    <div class="footer">Generated by HashGuardian</div>
</body>
</html>
